name: Build Project
on: 
  workflow_call:
    inputs:
      build_command: 
        description: command to build production version
        required: false
        default: npm run build
        type: string
      dependency_file_path: 
        description: path where dependency files are located
        required: false
        default: node_modules
        type: string
      dist_file_path: 
        description: path where build files are located
        required: false
        default: dist_files
        type: string      
    secrets:
      someSecret:
        description: somthing that would normally be needed for deployment
        required: true
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show command
        run: echo ${{ inputs.test_command }}
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: setup dependency cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dependency_file_path }}
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}          
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci        
      - name: build
        run: ${{ inputs.build_command }}
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: |
            ${{ inputs.dist_file_path }}
