name: Deploy
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
env:
  NONSECRETVALUE1: val1
  NONSECRETVALUE2: val2
jobs: 
  build:
    env:
      NONSECRETVALUE1: overridetov2
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: setup dependency cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}          
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: run tests
        run: npm run test
      - name: build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: |
            dist
  deploy:     
    needs: build
    runs-on: ubuntu-latest
    steps:   
      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: show contents
        run: ls
      - name: deploy
        run: |
          echo 'deploying now {{ env.NONSECRETVALUE1 }}'
          echo 'deploying now interpolation: $NONSECRETVALUE2'        