name: Deploy
on: 
  pull-request:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/*'  workflow-dispatch:
  push:
    branches: 
      - main
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: run tests
        run: npm run test
      - name: build
        run: npm run build
      - name: deploy
        run: echo 'deploying now'