name: Deploy
# run-name: Deploy by @${{ github.actor }}
on: 
  workflow_dispatch:
  push:
    branches: 
      - main
env:
  NONSECRETVALUE1: val1
  NONSECRETVALUE2: val2
jobs: 
  lint:
    uses: ./.github/workflows/lintProject.yml
    with: 
      dependency_file_path: node_modules
  test:
    needs: lint
    uses: ./.github/workflows/testProject.yml
    with: 
      test_command: 'npm run test'
  build:
    needs: lint
    environment: Development
    env:
      NONSECRETVALUE1: overridetov2
      FIRSTSECRET: ${{ secrets.REPOSECRET1 }}
      FIRSTENVSECRET: ${{ secrets.SECRET1 }}      
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: npm run build
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: dist-files
          path: |
            dist
  deploy:     
    needs: build
    runs-on: ubuntu-latest
    steps:   
      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: show contents
        run: ls
      - name: deploy
        run: |
          echo 'deploying now {{ env.NONSECRETVALUE1 }}'
          echo 'deploying now interpolation: $NONSECRETVALUE2'        