name: Deploy
on: 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with: 
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: lint
        run: npm run lint
      - name: run tests
        run: npm run test
      - name: build
        run: npm run build
