name: Test Project
on: 
  workflow_call:
    inputs:
      test_command: 
        description: command to execute tests
        required: false
        default: npm run test
        type: string
      dependency_file_path: 
        description: path where dependency files are located
        required: false
        default: node_modules
        type: string
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: show command
        run: echo ${{ inputs.test_command }}
      - name: setup dependency cache
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ inputs.dependency_file_path }}
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}          
      - name: install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci        
      - name: test
        run: ${{ inputs.test_command }}
